# Generated by Django 5.2.7 on 2025-10-07 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Ação', 'Ação'), ('BDR', 'BDR'), ('Cripto', 'Cripto')], max_length=10)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to='scanner.setor')),
            ],
        ),
    ]
