# Generated by Django 5.2.7 on 2025-10-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('preco_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentual_queda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grafico_base64', models.TextField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.ativo')),
            ],
        ),
    ]
